workflow:
  name: workflow pipeline
  jobs:
    dataset_etl_task:
      type: preprocess
      description: ETL process for dataset
      params:
        output_file: "data/preprocessed_data.csv"
    train_task:
      type: train
      description: Training the model
      params:
        train_data: "data/preprocessed_data.csv"
        model_output: "models/model.pkl"
    inference_task:
      type: inference
      description: Performing inference
      params:
        model_file: "models/model.pkl"
        test_data: "data/test_data.csv"
        metrics_output: "output/metrics.json"